pipeline {
    agent any
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_CREDENTIALS_ID = 'github-push-credentials' // Assuming this ID is used to store your GitHub credentials
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: '928fcb9f-ddfe-408f-9685-f6b994932552', url: 'https://github.com/madhanshiva/cicd-end-to-end'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker_id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        echo 'Build Docker Image'
                        docker build -t mvmadhan/cicd-e2e:${BUILD_NUMBER} .
                        '''
                    }
                }
            }
        }

        stage('Push the artifacts') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker_id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        echo 'Push to Repo'
                        docker push mvmadhan/cicd-e2e:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
        
        stage('Checkout K8S manifest SCM') {
            steps {
                git branch: 'main', credentialsId: '928fcb9f-ddfe-408f-9685-f6b994932552', url: 'https://github.com/madhanshiva/cicd-demo-manifests-repo.git'
            }
        }
        
        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-push-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh '''
                        # Change directory to deploy
                        cd deploy

                        # Update deploy.yaml file
                        sed -i "s/32/${BUILD_NUMBER}/g" deploy.yaml

                        # Configure git
                        git config user.name "Madhan Shiva"
                        git config user.email "madhanshiva@example.com"

                        # Pull latest changes and rebase
                        git pull origin main
                        git fetch origin
                        git rebase origin/main

                        # Add, commit and push changes
                        git add deploy.yaml
                        git commit -m "Updated the deploy yaml | Jenkins Pipeline" || true
                        git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/madhanshiva/cicd-demo-manifests-repo.git
                        git push origin main
                        '''
                    }
                }
            }
        }
    }
}
