pipeline {
  agent {
    docker {
      image 'node:16-alpine'
      label '' // Optional: specify a label if needed, or leave empty for any node
    }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
